Added the layers of configuration using static method in program, nee…
joni7777/netcore-seed pull request #11
Opened 2018-12-27 09:59 UTC by joni7777

…d to move to custom nupkg

2018-12-27 10:00 UTC, joni7777 commented
This PR is for adding the feature #2

2018-12-30 17:33 UTC, Meir017 requested changes

2018-12-30 17:33 UTC, Meir017 commented on BpSeed.Common/Constants.cs
> +    public class Constants
hmm?

2018-12-30 17:33 UTC, Meir017 commented on Components/Components.csproj
> +      <Reference Include="Microsoft.AspNetCore.Mvc.Core, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60">
just leave as
```xml
<PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.0" />
```

2018-12-30 17:33 UTC, Meir017 commented on Components/Components.csproj
> +      <Folder Include="Sample\AutoMapperProfiles" />
no need to add folders, creating `.cs` files is enough

2018-12-30 17:33 UTC, Meir017 commented on BpSeed.API/Program.cs
> +                .SetBasePath($"{Directory.GetCurrentDirectory()}/Config")
not sure we need this, you can just prefix the next lines with `./config/`

2018-12-31 08:25 UTC, joni7777 commented on BpSeed.API/Program.cs
> +                .SetBasePath($"{Directory.GetCurrentDirectory()}/Config")
Not working without it

2018-12-31 08:36 UTC, merged