Add serilog with default console logger.
joni7777/netcore-seed pull request #13
Opened 2018-12-31 13:41 UTC by joni7777

Add implementation for mattermost logger and splunk logger
Activate loggers by configuration.

Fix github issues #1 #3

2018-12-31 14:11 UTC, Meir017 commented on Bp.Logging/Bp.Logging.csproj
> +      <Reference Include="Microsoft.AspNetCore.Hosting.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60">
remove this

2018-12-31 14:17 UTC, Meir017 commented on Bp.Logging/Sinks/Http/BpBulkHttpSink.cs
> +            ConcurrentBag<LogEvent> existingLogs = new ConcurrentBag<LogEvent>();
why not something as simple as
```cs
var existingLogs = logs.ToArray();
logs = new ConcurrentBag<LogEvent>();
return existingLogs;
```

2018-12-31 14:19 UTC, Meir017 commented on Bp.Logging/Sinks/Splunk/BpSplunkSink.cs
> +            var joinedLogs = "";
use `StringBuilder` instead

2018-12-31 14:19 UTC, Meir017 commented on Bp.Logging/Sinks/Splunk/BpSplunkSink.cs
> +                joinedLogs += string.Format("{0}{0}", _formater.Format(log), Environment.NewLine);
this should probably be `string.Format("{0}{1}",` ...

2018-12-31 14:19 UTC, joni7777 commented on Bp.Logging/Sinks/Http/BpBulkHttpSink.cs
> +            ConcurrentBag<LogEvent> existingLogs = new ConcurrentBag<LogEvent>();
I was afraid of context switch like this:

```
var existingLogs = logs.ToArray();
// CONTEXT SWTICH (Logs added to logs variable)
// Some logs will be gone
logs = new ConcurrentBag<LogEvent>();
return existingLogs;
```

2018-12-31 14:56 UTC, Meir017 commented on Bp.Logging/SerilogInit.cs
> +            var splunkLogger = builder.Configuration.GetSection("SplunkLogger");
add `.Get<BpSplunkInfo>();` (`BpSplunkInfo` must contain a parameterless ctor and all properties should be `{ get; set; }`)

add package `Microsoft.Extensions.Configuration.Binder`

2019-01-06 19:36 UTC, Meir017 requested changes

2019-01-06 19:36 UTC, Meir017 commented on Bp.ApiRunner/Startup.cs
> +            app.UseSwaggerUI(c => { c.SwaggerEndpoint($"/swagger/{_service.Version}/swagger.json", $"{_service.Name} V{_service.Version}"); });
add property `SwaggerUrl` for this

2019-01-06 19:36 UTC, Meir017 commented on Bp.Logging/Sinks/Http/BpBulkHttpSink.cs
> +            while (logs.Count > 0)
use `.IsEmpty`

2019-01-06 19:36 UTC, Meir017 commented on Bp.Logging/Sinks/Mattermost/BpMattermostSinkExtensions.cs
> +            BpMattermostInfo bpMattermostInfo, ConcurrentBag<LogEvent> logs = null, Timer timer = null,
remove unused arguments

2019-01-06 19:36 UTC, Meir017 commented on Bp.Logging/Sinks/Splunk/BpSplunkLogFormatter.cs
> +            formattedLog.Append($"timestamp=\"{DateTime.Now.Millisecond.ToString()}\" ");
use `TotalMilliseconds`

2019-01-06 19:36 UTC, Meir017 commented on Bp.Logging/Sinks/Splunk/BpSplunkLogFormatter.cs
> +            foreach (KeyValuePair<string, LogEventPropertyValue> property in logEvent.Properties)
use `var`

2019-01-06 19:36 UTC, Meir017 commented on Bp.Logging/Sinks/Splunk/BpSplunkSink.cs
> +        private AuthenticationHeaderValue _basicAuth;
make readonly

2019-01-06 19:36 UTC, Meir017 commented on Components/Config/appsettings.json
> +    "CustomLoggers":{
don't use serilogs magic configuration, all manual

2019-01-06 19:36 UTC, Meir017 commented on Components/Sample/Implementations/SampleRouter.cs
> +        public SampleRouter([FromServices] ILogger<SampleRouter> logger)
remove `FromServices`

2019-01-07 17:22 UTC, Meir017 requested changes

2019-01-07 17:22 UTC, Meir017 commented on Bp.ApiRunner/Startup.cs
> +                c.SwaggerEndpoint($"/swagger/{_service.Version}/swagger.json", $"{_service.Name} V{_service.Version}"));
create a property for this `$"/swagger/{_service.Version}/swagger.json"`

2019-01-07 17:22 UTC, Meir017 commented on Bp.Logging/Sinks/Mattermost/BpMattermostInfo.cs
> +        public BpMattermostInfo(string protocol, string host, string port, string path)
remove this ctor

2019-01-07 17:22 UTC, Meir017 commented on Bp.ApiRunner/ServiceInfo.cs
> +        public ServiceInfo(string name, string version)
remove this ctor

2019-01-07 17:22 UTC, Meir017 commented on Bp.Logging/Sinks/Splunk/BpSplunkInfo.cs
> +        public BpSplunkInfo(string protocol, string host, string port, string username, string password, string index, string sourceType)
remove this ctor

2019-01-11 06:13 UTC, Meir017 commented on Bp.ApiRunner/Startup.cs
> +            app.UseMiddleware<EnrichWithRequestParamsMiddleware>();
create a static class with an extension method `UseEnrichWithRequestParams` in the same file as the `EnrichWithRequestParamsMiddleware` class

2019-01-11 06:13 UTC, Meir017 commented on Bp.ApiRunner/Startup.cs
> +
this looks like a sample class, remove it

2019-01-11 06:14 UTC, Meir017 commented on Bp.Logging/EnrichWithRequestParams/EnrichWithRequestParamsMiddleware.cs
> +            return Task.CompletedTask;
need to call `_next` to call the next middleware in the pipeline

2019-01-12 19:31 UTC, merged