Endpointer register
joni7777/netcore-seed pull request #19
Opened 2019-02-05 15:08 UTC by joni7777

2019-02-05 18:07 UTC, Meir017 requested changes

2019-02-05 18:07 UTC, Meir017 commented on Bp.ApiRunner/Runner.cs
> +	public class Runner
weird spacing in file

2019-02-05 18:07 UTC, Meir017 commented on Bp.EndPointer/Bp.EndPointer.csproj
> +      <Reference Include="Microsoft.AspNetCore.Hosting, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60">
shouldn't these be `PackageReference`?

2019-02-05 18:07 UTC, Meir017 commented on Bp.EndPointer/EndPointer.cs
> +			catch (HttpRequestException e) when (e.Message == "Connection refused")
there should be another catch clause for the Task Cancelled exception

2019-02-05 18:07 UTC, Meir017 commented on Bp.EndPointer/RegisterEndpointerHostedService.cs
> +		private string ParseServerAddress(string address)
add a description explaining what the input address looks like

2019-02-05 18:07 UTC, Meir017 commented on Bp.Logging/Sinks/Mattermost/BpMattermostSinkExtensions.cs
> +            LogEventLevel restrictedToMinimumLevel = LogEventLevel.Verbose)
I think the default should be `Error`

2019-02-05 18:07 UTC, Meir017 commented on Bp.Logging/Sinks/Splunk/BpSplunkInfo.cs
> +        public BpSplunkInfo()
no need for ctor

2019-02-06 09:11 UTC, joni7777 commented on Bp.ApiRunner/Runner.cs
> +	public class Runner
Looks kinda fine to me, can you be more specific about the problem?

2019-02-06 09:27 UTC, Meir017 commented on Bp.ApiRunner/Runner.cs
> +	public class Runner
tabs vs spaces...
never mind

2019-02-06 09:31 UTC, Meir017 commented on Bp.EndPointer/EndPointer.cs
> +			catch (HttpRequestException e) when (e.Message == "Connection refused")
maybe use `catch () when ()` ?
something like this:
```cs
catch (Exception e) 
when ((e is HttpRequestException && e.Message == "Connection refused")
    || e is TaskCanceledException)
{
    ....
    throw;
}
```

2019-02-06 12:31 UTC, Meir017 approved these changes

2019-02-06 13:04 UTC, merged